
public static class GlobalConstants
{
    public const int IncreaseStep = 175;
    public const int PermanentLoseReward = 50;
    public const int AdditionalLoseReward = 40;
    public const int PermanentVictoryReward = 200;
    public const int AdditionalVictoryReward = 160;
    public static string[] enemyNames = {
        "Ninja",
        "Lotus",
        "kraken",
        "Alexander",
        "Penelope",
        "Liam Garcia",
        "Miles",
        "Cascade",
        "Raven",
        "colada",
        "Resin",
        "Mia Kelly",
        "dracula",
        "Shiver",
        "Logan",
        "Lily",
        "Nova Cox",
        "Isla",
        "tequila",
        "Harlem",
        "Thunderbird",
        "Infinity",
        "Austin J.",
        "Ultra",
        "Insomnia",
        "Velvet",
        "Vixen",
        "Xenon",
        "David",
        "Amelia",
        "Connor",
        "Carson",
        "Ava",
        "Sophia",
        "young",
        "LucasGreen",
        "Mila",
        "Nora Adams",
        "John Baker",
        "Leon",
        "Lewis",
        "Leonidas",
        "cyrus",
        "Walker",
        "Mrs. Blonde",
        "Lee",
        "Hall",
        "Allen",
        "Ellie Wright",
        "Easton",
        "Kai Lopez",
        "HazelKing",
        "Madison",
        "Waylon",
        "Countess",
        "Enchantress",
        "Morgan",
        "Lillian",
        "Daniel",
        "Cougar",
        "Roulette",
        "Siren",
        "Shadow",
        "Enigma",
        "Stiletto",
        "Michael",
        "Mateo",
        "OwenRivera",
        "Paisley",
        "Samuel",
        "Mason Murphy",
        "Ivy Bailey",
        "Ethan",
        "Eliana",
        "Elena",
        "Everly",
        "Maya Cooper",
        "N. Reed",
        "Cobra",
        "Banshee",
        "Bruise",
        "Colton",
        "Mannequin",
        "Majesty",
        "Belladonna",
        "Mad Dog",
        "Half Pint",
        "Ian",
        "anomaly",
        "Calypso",
        "Beretta",
        "ronin",
        "Nova",
        "Mirage",
        "Axel",
        "Grace",
        "bender",
        "Lynch",
        "Rubble",
        "Firecracker",
        "Big Papa",
        "Geisha",
        "Bowser",
        "Goddess",
        "Emily",
        "Aria Hill",
        "Layla",
        "Reaper",
        "Carter",
        "Psycho",
        "Clink",
        "Black Beauty",
        "Ranger",
        "Colt",
        "Chloe",
        "Creep",
        "Jose Scott",
        "Wyatt",
        "Carbon",
        "Luca Perry",
        "Jaguar",
        "Aero",
        "Avenger",
        "Hornet",
        "Grizzly",
        "Wolverine",
        "Snake",
        "Wolf",
        "Falcon",
        "Camila",
        "Viper",
        "Ram",
        "Grip",
        "Black Mamba",
        "Bullet",
        "Olivia",
        "Emma Powell",
        "Charlotte",
        "Avery",
        "Isaac",
        "Caleb",
        "Lincoln",
        "Wildcat",
        "Jayden",
        "Anthony",
        "Gianna",
        "Hellcat",
        "Eleanor",
        "Elizabeth",
        "Scorpion",
        "Bennett",
        "Sofia",
        "Gabriel",
        "Ella Ross",
        "Ezra Wood",
        "Barnes",
        "Torpedo",
        "Luna Long",
        "Isabella",
        "Scarlett",
        "Harper",
        "Dylan",
        "Josiah",
        "Thomas",
        "Jenkins",
        "Maverick",
        "Abigail",
        "Panther",
        "Elias Price",
        "Evelyn",
        "Goshawk",
        "Charles",
        "Sanders",
        "Henderson",
        "Coleman",

    };
    public static string[] allEnemyNames = {
        // MAN
        "Noah",
        "Oliver",
        "Elijah",
        "James",
        "William",
        "Benjamin",
        "Henry",
        "Theodore",
        "Jack",
        "Levi",
        "Jackson",
        "Jacob",
        "Asher",
        "Aiden",
        "Joseph",
        "Leo",
        "Luke",
        "Julian",
        "Hudson",
        "Grayson",
        "Matthew",
        "Christopher",
        "Ezekiel",
        "Jaxon",
        "Isaiah",
        "Andrew",
        "Joshua",
        "Nathan",
        "Nolan",
        "Adrian",
        "Cameron",
        "Santiago",
        "Eli",
        "Aaron",
        "Ryan",
        "Angel",
        "Cooper",
        "Christian",
        "Landon",
        "Roman",
        "Brooks",
        "Jonathan",
        "Robert",
        "Jameson",
        "Everett",
        "Greyson",
        "Wesley",
        "Jeremiah",
        "Hunter",
        "Leonardo",
        "Jordan",
        "Bennett",
        "Silas",
        "Nicholas",
        "Parker",
        "Beau",
        "Weston",
        "Dominic",
        "Xavier",
        // WOMAN
        "Violet",
        "Aurora",
        "Riley",
        "Zoey",
        "Willow",
        "Emilia",
        "Stella",
        "Zoe",
        "Victoria",
        "Hannah",
        "Addison",
        "Leah",
        "Lucy",
        "Natalie",
        "Kinsley",
        "Delilah",
        "Claire",
        "Audrey",
        "Aaliyah",
        "Ruby",
        "Brooklyn",
        "Alice",
        "Aubrey",
        "Autumn",
        "Leilani",
        "Savannah",
        "Valentina",
        "Kennedy",
        "Madelyn",
        "Josephine",
        "Bella",
        "Skylar",
        "Genesis",
        "Sophie",
        "Hailey",
        "Sadie",
        "Natalia",
        "Quinn",
        "Caroline",
        "Allison",
        "Gabriella",
        "Anna",
        "Serenity",
        "Nevaeh",
        "Cora",
        "Ariana",
        "Emery",
        "Lydia",
        "Jade",
        "Sarah",
        "Eva",
        "Adeline",
        "Madeline",
        "Piper",
        "Rylee",
        "Athena",
        "Peyton",
        "Everleigh",
        // LASTNAMES
        "Smith",
        "Johnson",
        "Williams",
        "Brown",
        "Davis",
        "Miller",
        "Wilson",
        "Moore",
        "Taylor",
        "Anderson",
        "Thomas",
        "Jackson",
        "White",
        "Harris",
        "Martin",
        "Thompson",
        "Martinez",
        "Robinson",
        "Clark",
        "Rodriguez",
        "Hernandez",
        "Gonzalez",
        "Nelson",
        "Carter",
        "Mitchell",
        "Perez",
        "Roberts",
        "Turner",
        "Phillips",
        "Campbell",
        "Parker",
        "Evans",
        "Edwards",
        "Collins",
        "Stewart",
        "Sanchez",
        "Morris",
        "Rogers",
        "Richardson",
        "Howard",
        "Ward",
        "Torres",
        "Peterson",
        "Gray",
        "Ramirez",
        "James",
        "Watson",
        "Brooks",

        "Patterson",
        "Hughes",
        "Flores",
        "Washington",
        "Butler",
        "Simmons",
        "Foster",
        "Gonzales",
        "Bryant",
        "Alexander",
        "Russell",
        "Griffin",
        "Diaz",
        "Hayes",
        // Nicknames
        "Diablo",
        "Sasquatch",
        "Doom",
        "Scar",
        "Dragon",
        "Skinner",
        "Fester",
        "Slasher",
        "Surge",
        "Gargoyle",
        "Gunner",
        "Trooper",
        "Hash",
        "Tweek",
        "Hashtag",
        "Void",
        "Ironclad",
        "Wardon",
        "Wraith",
        "Zero",
        "Steel",
        "Kevlar",
        "Lightning",
        "Tito",
        "Titanium",
        "Hurricane",
        "Tempest",
        "Iron Heart",
        "Upsurge",
        "Admiral Tot",
        "Alpha",
        "Angel",
        "Baby Brown",
        "Back Bett",
        "Bad Bunny",
        "Beetle King",
        "Bit Sentinel",
        "Bitmap",
        "BlacKitten",
        "Blitz",
        "Bonzai",
        "Bowie",
        "Bowler",
        "Mr. Fury",
        "Ire",
        "Savage",
        "Cosmo",
        "Criss Cross",
        "Daffy Girl",
        "Dangle",
        "Day Hawk",
        "Desert Haze",
        "Desperado",
        "Devil Chick",
        "DiscoMate",
        "Dredd",
        "DuckDuck",
        "ElactixNova",
        "Ember Rope",
        "EyeShooter",
        "Fabulous",
        "Atilla",
        "Darko",
        "Terminator",
        "Maximus",
        "Geronimo",
    };
}
